#!/usr/local/bin/python2.5

''' A very simple script that emulates only the most useful bit of dos2unix's
behaviour - it removes the carriage return character, leaving just newline. It
does not alter any of the other characters in the file. It can be called with one
or two arguments - if one, the file is edited in place (sort of), otherwise the
second argument is the name of the output file. '''

import re, sys, os

if len(sys.argv) == 1:
    sys.stderr.write("No file to work on\n")
    exit(1)
else:
    infile = sys.argv[1]
    if len(sys.argv) == 3:
        outfile = sys.argv[2]
        inplace = False
    else:
        outfile = infile + 'tmp'
        inplace = True

outfh = open(outfile, 'w')
for line in open(infile):
    outfh.write(re.sub(r'\r\n$', '\n', line))
    
outfh.close()

if inplace is True:
    import shutil
    shutil.copy(outfile, infile)
