# -*- mode: shell-script -*-

if [ -f /packages/dsol/etc/bash_profile.dsol ]
then
    . /packages/dsol/etc/bash_profile.dsol
fi

if [ -d ~/bin ]
then
    PATH=~/bin:${PATH}
fi

if [ -f ~/.bash_${USER} ]
then
    . ~/.bash_${USER}
fi

## Don't change anything above this line!

