#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1226314424.494591
__CHEETAH_genTimestamp__ = 'Mon Nov 10 10:53:44 2008'
__CHEETAH_src__ = 'ris_volume_comcitn.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Nov 10 10:52:56 2008'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ris_volume_comcitn(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<comcitn>''')
        write('''<TY>BOOK</TY>''')
        if len(VFFSL(SL,"author_attribution_set",True)) > 0: # generated from line 3, col 1
            write('''<AU>''')
            _v = VFN(VFFSL(SL,"author_attribution_set",True)[0],"namefromdata",True) # '$author_attribution_set[0].namefromdata' on line 4, col 5
            if _v is not None: write(_filter(_v, rawExpr='$author_attribution_set[0].namefromdata')) # from line 4, col 5.
            write('''</AU>''')
            if len(VFFSL(SL,"author_attribution_set",True)) > 1: # generated from line 5, col 1
                for author in VFFSL(SL,"author_attribution_set",True)[1:]: # generated from line 6, col 1
                    write('''<A2>''')
                    _v = VFFSL(SL,"author.namefromdata",True) # '$author.namefromdata' on line 7, col 5
                    if _v is not None: write(_filter(_v, rawExpr='$author.namefromdata')) # from line 7, col 5.
                    write('''</A2>''')
        write('''<TI>''')
        _v = VFFSL(SL,"title",True) # '$title' on line 11, col 5
        if _v is not None: write(_filter(_v, rawExpr='$title')) # from line 11, col 5.
        write('''</TI>''')
        write('''<CY>''')
        _v = VFFSL(SL,"city",True) # '$city' on line 12, col 5
        if _v is not None: write(_filter(_v, rawExpr='$city')) # from line 12, col 5.
        write('''</CY>''')
        write('''<PBL>''')
        _v = VFFSL(SL,"publisher",True) # '$publisher' on line 13, col 6
        if _v is not None: write(_filter(_v, rawExpr='$publisher')) # from line 13, col 6.
        write('''</PBL>''')
        write('''<Y2>''')
        _v = VFFSL(SL,"filepubdate",True) # '$filepubdate' on line 14, col 5
        if _v is not None: write(_filter(_v, rawExpr='$filepubdate')) # from line 14, col 5.
        write('''</Y2>''')
        write('''<Y1>''')
        _v = VFN(VFN(VFFSL(SL,"pubdate",True),"replace",False)('[', ''),"replace",False)(']', '') # "$pubdate.replace('[', '').replace(']', '')" on line 15, col 5
        if _v is not None: write(_filter(_v, rawExpr="$pubdate.replace('[', '').replace(']', '')")) # from line 15, col 5.
        write('''</Y1>''')
        write('''<SN>''')
        _v = VFFSL(SL,"ISBN",True) # '$ISBN' on line 16, col 5
        if _v is not None: write(_filter(_v, rawExpr='$ISBN')) # from line 16, col 5.
        write('''</SN>''')
        write('''<T2>Literature Online</T2>''')
        write('''<UR>''')
        _v = VFFSL(SL,"idref",True) # '$idref' on line 18, col 5
        if _v is not None: write(_filter(_v, rawExpr='$idref')) # from line 18, col 5.
        write('''</UR>''')
        write('''<N1a>''')
        _v = VFN(VFFSL(SL,"excludere",True),"sub",False)('', VFFSL(SL,"notes",True)) # "$excludere.sub('', $notes)" on line 19, col 6
        if _v is not None: write(_filter(_v, rawExpr="$excludere.sub('', $notes)")) # from line 19, col 6.
        write('''</N1a>''')
        write('''<N1b>''')
        _v = VFFSL(SL,"filecity",True) # '$filecity' on line 20, col 6
        if _v is not None: write(_filter(_v, rawExpr='$filecity')) # from line 20, col 6.
        write(''', ''')
        _v = VFFSL(SL,"filepublisher",True) # '$filepublisher' on line 20, col 17
        if _v is not None: write(_filter(_v, rawExpr='$filepublisher')) # from line 20, col 17.
        write(''', ''')
        _v = VFFSL(SL,"filepubdate",True) # '$filepubdate' on line 20, col 33
        if _v is not None: write(_filter(_v, rawExpr='$filepubdate')) # from line 20, col 33.
        write('''</N1b>''')
        write('''<N1c>''')
        _v = VFFSL(SL,"copyright",True) # '$copyright' on line 21, col 6
        if _v is not None: write(_filter(_v, rawExpr='$copyright')) # from line 21, col 6.
        write('''</N1c>''')
        write('''</comcitn>''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ris_volume_comcitn= 'respond'

## END CLASS DEFINITION

if not hasattr(ris_volume_comcitn, '_initCheetahAttributes'):
    templateAPIClass = getattr(ris_volume_comcitn, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ris_volume_comcitn)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ris_volume_comcitn()).run()


