#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0rc8'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 8)
__CHEETAH_genTime__ = 1226314424.140254
__CHEETAH_genTimestamp__ = 'Mon Nov 10 10:53:44 2008'
__CHEETAH_src__ = 'ris_poem_comcitn_redux.tmpl'
__CHEETAH_srcLastModified__ = 'Tue Nov  6 15:33:48 2007'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ris_poem_comcitn_redux(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<comcitn>''')
        write('''<TY>CHAP</TY>''')
        write('''<A1>''')
        _v = " / ".join([VFFSL(SL,"a.namefromdata",True) for a in VFFSL(SL,"author_attribution_set",True)]) # '${" / ".join([$a.namefromdata for $a in $author_attribution_set])}' on line 3, col 5
        if _v is not None: write(_filter(_v, rawExpr='${" / ".join([$a.namefromdata for $a in $author_attribution_set])}')) # from line 3, col 5.
        write('''</A1>''')
        write('''<T1>''')
        _v = VFFSL(SL,"title",True) # '$title' on line 4, col 5
        if _v is not None: write(_filter(_v, rawExpr='$title')) # from line 4, col 5.
        write('''</T1>''')
        write('''<T2>''')
        _v = VFN(VFFSL(SL,"volume_set",True)[0],"title",True) # '$volume_set[0].title' on line 5, col 5
        if _v is not None: write(_filter(_v, rawExpr='$volume_set[0].title')) # from line 5, col 5.
        write('''</T2>''')
        write('''<PBL>''')
        _v = VFN(VFFSL(SL,"volume_set",True)[0],"publisher",True) # '$volume_set[0].publisher' on line 6, col 6
        if _v is not None: write(_filter(_v, rawExpr='$volume_set[0].publisher')) # from line 6, col 6.
        write('''</PBL>''')
        write('''<Y1>''')
        _v = VFN(VFFSL(SL,"volume_set",True)[0],"pubdate",True) # '$volume_set[0].pubdate' on line 7, col 5
        if _v is not None: write(_filter(_v, rawExpr='$volume_set[0].pubdate')) # from line 7, col 5.
        write('''</Y1>''')
        write('''<T3>Literature Online</T3>''')
        write('''<ID>''')
        _v = VFFSL(SL,"currentidref",True) # '$currentidref' on line 9, col 5
        if _v is not None: write(_filter(_v, rawExpr='$currentidref')) # from line 9, col 5.
        write('''</ID>''')
        write('''</comcitn>''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ris_poem_comcitn_redux= 'respond'

## END CLASS DEFINITION

if not hasattr(ris_poem_comcitn_redux, '_initCheetahAttributes'):
    templateAPIClass = getattr(ris_poem_comcitn_redux, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ris_poem_comcitn_redux)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ris_poem_comcitn_redux()).run()


